language: node_js
node_js:
- node
jobs:
  include:
  - stage: "@rail-style/fragments"
    install:
    - npm install --prefix packages/fragments
    script:
    - npm run-script babelCoverage --prefix packages/fragments
    - npm run-script babelTests --prefix packages/fragments
    - npm run-script jasmine --prefix packages/fragments
    - npm run-script babel --prefix packages/fragments
    - npm run-script uglify-js --prefix packages/fragments
    deploy:
    - provider: script
      script: echo $NPM_TOKEN > ~/.npmrc && npm publish packages/fragments
      skip_cleanup: true
      on:
        branch: master
        repo: train-of-consequences/rail-style
env:
  secure: c7azoxIL9rlZuEbFL34N29wXkIy11LvPgPcFD5XTnFIiXtQ4mvGMsRNggD4Zudc4RRbDFKQ38OWY6QxB0z3wJkzn02O77udLDmj/oX997dVUEAeKYE4ADP31RreffDWaoO/eQGNlG3g9SD18belUDbPA2PZrsAJLEipoERdPuBQCnjgxvpUMKKhyBW9DX7EEH3ciautba22yU61jSCP+xOqz95N62zgZjV2kuxvIgPsM8X44pRVga3IZox6SrOYBkoqV8OWJoH6aZXjzlqQi24hZjsUZJRveRDQ7BxflqKYTcl2JddozygX4kz1/Eg3r1Z6lni/2mSqRlmaxeXibxuyLW3fRP5fdRQNinpNyLzFFUvLKd53gH3GywozycD7N+ES0CvBrKQJfTNI/vd+a1xRJVEGJ/P1CuBi3vC87ePA/kxR/yaDQWfWyBJ+EXdb7decO727pRJ7AeByel4d/yWUuwqFAWzfMOXJBHGDUWagCzJPewDu3IFy5HvBTldTMme2lCOxnyZGH2F6+lI+JDdZRy1kyhpf06H7pvglL6pkZlK0Qnu3JBXx2DYUGEU85oFwesB3QXH/amjwPIiSOhrFbwz2BsTr4FL3b92LpaGX+NnwDx1IF6NeI9wAS5TrFt/+MXYf2XyuovK5H+J6zD+X6dF8p+uAHA2GO1rrGzRA=
