language: node_js
node_js:
- node
jobs:
  include:
  - stage: "@rail-style/fragments"
    install:
    - npm install --prefix packages/fragments
    script:
    - npm run-script babel --prefix packages/fragments
    - npm run-script babelTests --prefix packages/fragments
    - npm run-script jasmine --prefix packages/fragments
    - npm run-script uglify-js --prefix packages/fragments
    deploy:
    - provider: script
      script: echo $NPM_TOKEN > ~/.npmrc && npm publish packages/fragments
      skip_cleanup: true
      on:
        branch: master
        repo: train-of-consequences/rail-style
env:
  secure: qEeayhA//cTnBN+yS1G6lqqpJttMAwEyuiRBt+JLCxHUXZJFXvgwrI74KFNun3lVfh60owzLgPfCsBuP+AcEquigJEQw1fM+rfBoyEn1JkxmWYXnTNqQelkp6fXcb21zVziN5F9kR+ysqYuhhYajqFvdBRe7IUvvE50ZIRNBLBefacfoNRZ0HZwsdLjV+vZjWYkOgGmTIQdxfYcCi1R4lnzgCU++FU4nJxCA5ZsFIySrnaWf78BHSEHgmeQpEqQBLhdH1YgX7pdUUuKn7uDK9L41ML+GZ4GAfV4slGc2Nk7+SgJvrbqD2zRtFFj8Xdg4X2M9Gq8KAkdh+QBipTB03v+WgURdm37SXBaztNI6ne7PCLLHpzZpsibxMFmYshEt86ZIvFXdiqkxoHcWuelviJnlV7fMZxKUeqLZAPTvHLO+zWxWtBXvYaNQYybvgtFyZAOYy8VG/4vWJ8d8/djJIE0eYDcirdLa4yfVZDBlqOaatYxNmolHhcR4BamyZ40HTnVgmgfAyyzAcGSu3Y8YMihr5E0U9HUHhcTNMI7vD2WSJ+7wFpBOYoeFVgizhQWm953ZzzLiZ1fuBEnbXuLhVqbQvjrYZTNtlHWmK2rZTPDSTw7toYGdMNJacZjZjdLoG7HTbwZ7nKSHno3hXm2PZhLMgUsi0CYZXq3pilDk3tw=
